name: static_micro_cms
description: A package that helps you create a webpage with Jamstack using microCMS
version: 0.2.1
homepage: https://github.com/organic-nailer/static_micro_cms

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotenv: ^4.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2


flutter:

