name: static_micro_cms
description: A package that helps you create a webpage with Jamstack using microCMS
version: 0.1.0
homepage: https://github.com/organic-nailer/static_micro_cms

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  build: ^2.1.1
  dotenv: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

